version: '3.1'
services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-tech-test
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"